### ISSUE TITLE
how to fliter significant loops

### ISSUE THREAD

**Issue by BenxiaHu** [tmlagler/hicACT#1]
Hi,
    I have run HiC-ACT to post-process the Fit-HiC2 loops. here is the screenshot for HiC-ACT result:
    
![image](https://user-images.githubusercontent.com/12387462/107704706-b5b93580-6c8b-11eb-94e1-1d0b1cb26c6b.png)

My question is on what threshold (_**ACT_pvalue**_) was set to get signifcant loops from HiC-ACT result?
    
Best,

**Comment by tmlagler** [comment]
The input parameter _thres_ specifies the threshold used to determine which Fit-Hi-C2 _p_-values are adjusted by HiC-ACT, so whatever value you provided for _thres_ was the threshold used. Does that help answer your question?

**Comment by BenxiaHu** [comment]
So I can use the _**thres**_ to define significant loops called by HiC-ACT, right?

**Comment by tmlagler** [comment]
I wouldn't necessarily suggest that. _**thres**_ is specifying which _p_-values to adjust, and is not used to define significance. For instance, if you want to define significant loops as those with _p_-value < 1e-12, you would want to set _**thres**_ to be less than that (1e-6 - 1e-3), then define significance based on the adjusted _p_-values. HiC-ACT borrows information from neighboring bin pairs to potentially identify significant interactions missed by Fit-HiC-2, so if  _**thres**_ is very small or close to your desired significance threshold (e.g. 1e-10), you're not giving HiC-ACT a chance to do that. Also, it is unlikely that all _p_-values adjusted by HiC-ACT will be significant, and therefore it is important to define significant loops after running HiC-ACT.

**Comment by BenxiaHu** [comment]
thanks.
I set _**thres**_ to 1.7e-4 based on (https://ars.els-cdn.com/content/image/1-s2.0-S0002929721000094-mmc1.pdf).

as you said "_**Also, it is unlikely that all p-values adjusted by HiC-ACT will be significant, and therefore it is important to define significant loops after running HiC-ACT.**_", do you have any suggestion to define significant loops called by HiC-ACT?

**Comment by tmlagler** [comment]
Okay, great. Defining significant loops is a bit of a personal preference, depending on how conservative you want to be. I'd suggest basing the significance threshold off of the size of your data. Similar to what we did, perhaps consider _p_ < 0.001/(# interactions) (a Bonferroni correction of 0.001).

**Comment by BenxiaHu** [comment]
thanks. I will try that threshold to define significant loops called by HiC-ACT.
