### ISSUE TITLE
can run hicACT chromosome by chromosome?

### ISSUE THREAD

**Issue by sckinta** [tmlagler/hicACT#2]
If i understand ACT adjust correctly,  hicACT adjust p-value in neighbouring interactions? I am wondering whether I can run hicACT for each chromosome independently? It takes too much memory and time to run as a whole genome.

**Comment by tmlagler** [comment]
Yes, HiC-ACT should be run on each chromosome separately.

**Comment by sckinta** [comment]
Thanks!
